FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY cli ./cli

RUN mkdir -p /app/logs
RUN chmod -R 755 /app/logs

ENTRYPOINT ["python", "-m"]